M48
; DRILL file {KiCad 9.0.7} date 2026-06-20T16:28:14-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-20T16:28:14-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X151.22Y-42.0
X157.0Y-42.0
T2
X146.2Y-39.6
M30
